### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by r4c3**
a lot of ui changes. I'll do the merge conflicts

### CODE REVIEW

**Comment by r4c3** [comment]
dont approve/review this yet btw im not done

**Comment by r4c3** [comment]
Finished bySearch. Go ahead and review but I'll still be working on the frontend

**Review by RiRah123 — APPROVED** [review]

**Comment by RiRah123** [comment]
> at this point Rian's profile commits are connected, except for the attempedProblems stuff which is not being stored on the user object yet. Aaron's bySearch is half connected, the frontend elements are there but not styled nor connected to the props of the ProblemBodys. Tomorrow I connect bySearch by 1pm. Likely that I can set up attemptedProblems as well, but will probably proritize landing and profile UI first. TwoSum problem created, works but still need to add tags to the Create page and to the schema. Don't review y

**Comment by RiRah123** [comment]
Sorry, did not mean to close this

**Comment by r4c3** [comment]
> Sorry, did not mean to close this. I will try to reopen this if possible

no prob, I did the same thing multiple times

**Review by Giovanni1014 — APPROVED** [review]
legit

**Comment by r4c3** [comment]
Closed a lot of issues with that one. Great work @aaronliuo @RiRah123 @Giovanni1014

**Comment by RiRah123** [comment]
Nice work!

**Pull request merged**
