### PR TITLE
pre-demo finishes

### PR DESCRIPTION
**Pull request by r4c3**
don't need immmediate approval. I will be making commits to this throughout monday. Main purpose is so people know what I'm working on and have the option to merge on demand if needed

### CODE REVIEW

**Review by Giovanni1014 — APPROVED** [review]
thanks man, good stuff

**Comment by r4c3** [comment]
> thanks man, good stuff

thanks, and btw im still working on the raw/cooked status stuff in the problems.js class component, likely done in like 30min

**Review by RiRah123 — APPROVED** [review]

**Comment by RiRah123** [comment]
> > thanks man, good stuff
> 
> thanks, and btw im still working on the raw/cooked status stuff in the problems.js class component, likely done in like 30min

Nice work. You can merge the branch whenever you are finished. Also, if you got time, can you try to get the progress bar on profile page working? Like I just put 35% for each bar, but it supposed to be the number of problems eaten for the specified difficulty/total problems for the specified difficulty.

**Comment by Giovanni1014** [comment]
@RiRah123 I'm working on that

**Pull request merged**
