### PR TITLE
fetchTestCases, questionID, distributed worker system, submission schema, result format, fixed bugs

### PR DESCRIPTION
**Pull request by Giovanni1014**
1. finished fetchTestCases, now the testUserCode function would download the testcases for a question before running the code. 
2. The code-testing part is all fixed and can now run the code on the specified questionID. 
3. We now call testUserCode with only questionID instead of questionName and testCases.
4. Modulize database connection (I think its a standard practice)
5. Fixed some error handling (but there's still a lot more to fix)

### CODE REVIEW

**Comment by Giovanni1014** [comment]
https://user-images.githubusercontent.com/46436786/202642333-3abcbd16-e447-4e1d-ba7b-8787680e3e72.mov

**Comment by r4c3** [comment]
Dang brother, good work, I'll review

**Comment by r4c3** [comment]
accidentally closed pr bc of a misclick, reopened, will test and review by tmr at like 1pm, busy rn

**Review by r4c3 — APPROVED** [review]
Tested and working. In worker folder do "npm i jszip rimraf" to test

**Review by aaronliuo — APPROVED** [review]
Good work!

**Pull request merged**
